src/Sm/JobsBundle/Form/JobType.php
<?php

namespace Sm\JobsBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Sm\JobsBundle\Entity\Job;

class JobType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('type', 'choice', array(
                    'choices' => Job::getTypes(),
                    'expanded' => true,
                    'data' => 'full-time'
                    // 'label_attr' => array('class' => 'col-sm-4')
                )
            )
            ->add('company', 'text', array(
                    // 'label_attr' => array('class' => 'col-sm-4')
                )
            )
            ->add('file', 'file', array(
                    'label' => 'Company logo',
                    // 'label_attr' => array('class' => 'col-sm-4'),
                    'required' => false
                )
            )
            ->add('url', null, array(
                    // 'label_attr' => array('class' => 'col-sm-4')
                )
            )
            ->add('position', null, array(
                    // 'label_attr' => array('class' => 'col-sm-4')
                )
            )
            ->add('location', null, array(
                    // 'label_attr' => array('class' => 'col-sm-4')
                )
            )
            ->add('description', null, array(
                    // 'label_attr' => array('class' => 'col-sm-4')
                )
            )
            ->add('how_to_apply', null, array(
                    'label' => 'How to apply?'
                    // 'label_attr' => array('class' => 'col-sm-4')
                )
            )
            ->add('is_public', null, array(
                    'label' => 'Public?'
                    // 'label_attr' => array('class' => 'col-sm-4')
                )
            )
            ->add('email', null, array(
                    // 'label_attr' => array('class' => 'col-sm-4')
                )
            )
            ->add('category', null, array(
                    // 'label_attr' => array('class' => 'col-sm-4')
                )
            )
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Sm\JobsBundle\Entity\Job'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'Sm_Jobsbundle_jobtype';
    }
}

src/Sm/JobsBundle/Controller/JobController.php
<?php

namespace Sm\JobsBundle\Controller;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sm\JobsBundle\Entity\Job;
use Sm\JobsBundle\Form\JobType;


/**
 * Class JobController
 * @package Sm\JobsBundle\Controller
 */
class JobController extends Controller
{
    /**
     * Create a form for job creation
     * @param Job $entity The entity
     * @return \Symfony\Component\Form\Form The form
     */
    private function createCreateForm(Job $entity)
    {
        $form = $this->createForm(new JobType(), $entity, array(
            'action' => $this->generateUrl('Sm_job_create'),
            'method' => 'POST',
        ));

        $form->add('submit', 'submit', array('label' => 'Create'));

        return $form;
    }

    /**
     * CREATE AN EDIT FORM
     *
     * @param Job $entity The entity
     * @return \Symfony\Component\Form\Form The form
     */
    private function createEditForm(Job $entity)
    {
        $form = $this->createForm(new JobType(), $entity, array(
            'action' => $this->generateUrl('Sm_job_update', array('id' => $entity->getId())),
            'method' => 'PUT',
        ));

        $form->add('submit', 'submit', array('label' => 'Update'));

        return $form;
    }

    /**
     * CREATE A PUBLISH FORM
     *
     * @param $token
     * @return \Symfony\Component\Form\Form
     */
    private function createPublishForm($token)
    {
        return $this->createFormBuilder(array('token' => $token))
            ->add('token', 'hidden')
            ->getForm()
            ;
    }

    /**
     * CREATE A DELETE FORM
     *
     * @param $token
     * @return \Symfony\Component\Form\Form
     */
    private function createDeleteForm($token)
    {
        return $this->createFormBuilder(array('token' => $token))
            ->add('token', 'hidden')
            ->getForm()
            ;
    }


    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getEntityManager();

        $categories = $em->getRepository('JobsBundle:Category')->getWithJobs();

        foreach($categories as $category)
        {
            $category->setActiveJobs($em->getRepository('JobsBundle:Job')->getActiveJobs($category->getId(), $this->container->getParameter('max_jobs_per_category_on_homepage')));

            $category->setMoreJobs($em->getRepository('JobsBundle:Job')->countActiveJobs($category->getId()) - $this->container->getParameter('max_jobs_per_category_on_homepage'));
        }

        return $this->render('JobsBundle:Job:index.html.twig', array(
            'categories' => $categories
        ));
    }

    /**
     * Creates a new Job entity.
     */
    public function createAction(Request $request)
    {
        $entity  = new Job();
        $entity->setCompany('Company One'); // should pre-populate field

        $form = $this->createForm(new JobType(), $entity);

        $form->handleRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getEntityManager();

            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('Sm_job_preview', array(
                'company' => $entity->getCompanySlug(),
                'location' => $entity->getLocationSlug(),
                'token' => $entity->getToken(),
                'position' => $entity->getPositionSlug()
            )));
        }

        return $this->render('JobsBundle:Job:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView()
        ));
    }


    /**
     * Displays a form to create a new Job entity.
     *
     */
    public function newAction()
    {
        $entity = new Job();
        $form   = $this->createCreateForm($entity);

        return $this->render('JobsBundle:Job:new.html.twig', array(
            'entity' => $entity,
            'form'   => $form->createView(),
        ));
    }

    /**
     * Finds and displays a Job entity.
     *
     */
    public function showAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $entity = $em->getRepository('JobsBundle:Job')->getActiveJob($id);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Job entity.');
        }

        $deleteForm = $this->createDeleteForm($id);

        return $this->render('JobsBundle:Job:show.html.twig', array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
        ));
    }


    /**
     * Displays a form to edit an existing Job entity.
     *
     */
    public function editAction($token)
    {
        $em = $this->getDoctrine()->getEntityManager();

        $entity = $em->getRepository('JobsBundle:Job')->findOneByToken($token);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Job entity.');
        }

        $editForm = $this->createForm(new JobType(), $entity);
        $deleteForm = $this->createDeleteForm($token);

        return $this->render('JobsBundle:Job:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    public function updateAction($token)
    {
        $em = $this->getDoctrine()->getEntityManager();

        $entity = $em->getRepository('JobsBundle:Job')->findOneByToken($token);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Job entity.');
        }

        $editForm   = $this->createForm(new JobType(), $entity);
        $deleteForm = $this->createDeleteForm($token);

//        $request = $this->getRequest();
//
//        $editForm->bindRequest($request);

        if ($editForm->isValid()) {
            $em->persist($entity);
            $em->flush();

            return $this->redirect($this->generateUrl('Sm_job_preview', array(
                'company' => $entity->getCompanySlug(),
                'location' => $entity->getLocationSlug(),
                'token' => $entity->getToken(),
                'position' => $entity->getPositionSlug()
            )));
        }

        return $this->render('JobsBundle:Job:edit.html.twig', array(
            'entity'      => $entity,
            'edit_form'   => $editForm->createView(),
            'delete_form' => $deleteForm->createView(),
        ));
    }

    public function deleteAction($token)
    {
//        $form = $this->createDeleteForm($token);

//        $task = ...;
        $form = $this->createDeleteForm($token);



//        $request = $this->getRequest();

//        $form->bindRequest($request);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getEntityManager();
            $entity = $em->getRepository('JobsBundle:Job')->findOneByToken($token);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Job entity.');
            }

            $em->remove($entity);
            $em->flush();
        }

        return $this->redirect($this->generateUrl('Sm_job'));
    }



    /**
     * @param $token
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function previewAction($token)
    {
        $em = $this->getDoctrine()->getEntityManager();

        $entity = $em->getRepository('JobsBundle:Job')->findOneByToken($token);

        if (!$entity) {
            throw $this->createNotFoundException('Unable to find Job entity.');
        }



        $deleteForm = $this->createDeleteForm($entity->getId());
        $publishForm = $this->createPublishForm($entity->getToken());

        return $this->render('JobsBundle:Job:show.html.twig', array(
            'entity'      => $entity,
            'delete_form' => $deleteForm->createView(),
            'publish_form' => $publishForm->createView(),
        ));
    }

    public function publishAction($token)
    {
        $form = $this->createPublishForm($token);
//        $request = $this->getRequest();

//        $form->bindRequest($request);
        $em = $this->getDoctrine()->getEntityManager();
        $entity = $em->getRepository('JobsBundle:Job')->findOneByToken($token);

        if ($form->isValid()) {
            $em = $this->getDoctrine()->getEntityManager();
            $entity = $em->getRepository('JobsBundle:Job')->findOneByToken($token);

            if (!$entity) {
                throw $this->createNotFoundException('Unable to find Job entity.');
            }

            $entity->publish();
            $em->persist($entity);
            $em->flush();

            $this->get('session')->setFlash('notice', 'Your job is now online for 30 days.');
        }

        return $this->redirect($this->generateUrl('Sm_job_preview', array(
            'company' => $entity->getCompanySlug(),
            'location' => $entity->getLocationSlug(),
            'token' => $entity->getToken(),
            'position' => $entity->getPositionSlug()
        )));
    }

}

src/Sm/JobsBundle/Resources/views/Job/admin.html.twig
<div id="job_actions">
    <h3>Admin</h3>
    <ul>
        {% if not job.isActivated %}
            <li><a href="{{ path('Sm_job_edit', { 'token': job.token }) }}">Edit</a></li>
            <li>
                <form action="{{ path('Sm_job_publish', { 'token': job.token }) }}" method="post">
                    {{ form_widget(publish_form) }}
                    <button type="submit">Publish</button>
                </form>
            </li>
        {% endif %}
        <li>
            <form action="{{ path('Sm_job_delete', { 'token': job.token }) }}" method="post">
                {{ form_widget(delete_form) }}
                <button type="submit" onclick="if(!confirm('Are you sure?')) { return false; }">Delete</button>
            </form>
        </li>
        {% if job.isActivated %}
            <li {% if job.expiresSoon %} class="expires_soon" {% endif %}>
                {% if job.isExpired %}
                    Expired
                {% else %}
                    Expires in <strong>{{ job.getDaysBeforeExpires }}</strong> days
                {% endif %}

                {% if job.expiresSoon %}
                    - <a href="">Extend</a> for another 30 days
                {% endif %}
            </li>
        {% else %}
            <li>
                [Bookmark this <a href="{{ url('Sm_job_preview', { 'token': job.token, 'company': job.companyslug, 'location': job.locationslug, 'position': job.positionslug }) }}">URL</a> to manage this job in the future.]
            </li>
        {% endif %}
    </ul>
</div>

src/Sm/JobsBundle/Resources/views/Job/edit.html.twig
{% extends 'JobsBundle::layout.html.twig' %}

{% form_theme edit_form _self %}

{% block field_errors %}
    {% spaceless %}
        {% if errors|length > 0 %}
            <ul>
                {% for error in errors %}
                    <li>{{ error.messageTemplate|trans(error.messageParameters, 'validators') }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endspaceless %}
{% endblock field_errors %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/Jobs/css/job.css') }}" type="text/css" media="all" />
{% endblock %}

{% block content %}
    <h1>Job edit</h1>
    <form action="{{ path('Sm_job_update', { 'token': entity.token }) }}" method="post" {{ form_enctype(edit_form) }}>
        <table id="job_form">
            <tfoot>
            <tr>
                <td colspan="2">
                    <input type="submit" value="Preview your job" />
                </td>
            </tr>
            </tfoot>
            <tbody>
            <tr>
                <th>{{ form_label(edit_form.category) }}</th>
                <td>
                    {{ form_errors(edit_form.category) }}
                    {{ form_widget(edit_form.category) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.type) }}</th>
                <td>
                    {{ form_errors(edit_form.type) }}
                    {{ form_widget(edit_form.type) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.company) }}</th>
                <td>
                    {{ form_errors(edit_form.company) }}
                    {{ form_widget(edit_form.company) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.file) }}</th>
                <td>
                    {{ form_errors(edit_form.file) }}
                    {{ form_widget(edit_form.file) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.url) }}</th>
                <td>
                    {{ form_errors(edit_form.url) }}
                    {{ form_widget(edit_form.url) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.position) }}</th>
                <td>
                    {{ form_errors(edit_form.position) }}
                    {{ form_widget(edit_form.position) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.location) }}</th>
                <td>
                    {{ form_errors(edit_form.location) }}
                    {{ form_widget(edit_form.location) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.description) }}</th>
                <td>
                    {{ form_errors(edit_form.description) }}
                    {{ form_widget(edit_form.description) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.how_to_apply) }}</th>
                <td>
                    {{ form_errors(edit_form.how_to_apply) }}
                    {{ form_widget(edit_form.how_to_apply) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.is_public) }}</th>
                <td>
                    {{ form_errors(edit_form.is_public) }}
                    {{ form_widget(edit_form.is_public) }}
                    <br /> Whether the job can also be published on affiliate websites or not.
                </td>
            </tr>
            <tr>
                <th>{{ form_label(edit_form.email) }}</th>
                <td>
                    {{ form_errors(edit_form.email) }}
                    {{ form_widget(edit_form.email) }}
                </td>
            </tr>
            </tbody>
        </table>

        {{ form_rest(edit_form) }}
    </form>
{% endblock %}

src/Sm/JobsBundle/Resources/views/Job/index.html.twig
{# {% extends 'JobsBundle::layout.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/Jobs/css/jobs.css') }}" type="text/css" media="all" />
{% endblock %}

{% block content %}
    <div id="jobs">
        {% for category in categories %}
            <div class="category_{{ category.slug }}">
                <div class="category">
                    <div class="feed">
                        <a href="">Feed</a>
                    </div>
                    <h1><a href="{{ path('SmJobsBundle_category', { 'slug': category.slug }) }}">{{ category.name }}</a></h1>
                </div>
                {% include 'JobsBundle:Job:list.html.twig' with {'jobs': category.activejobs} %}
                {% if category.morejobs %}
                    <div class="more_jobs">
                        and <a href="{{ path('SmJobsBundle_category', { 'slug': category.slug }) }}">{{ category.morejobs }}</a>
                        more...
                    </div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}
 #}

src/Sm/JobsBundle/Resources/views/Job/list.html.twig
<table class="jobs table table-striped table-hover">
    <h1>hello</h1>
    {% for entity in jobs %}
        <tr class="{{ cycle(['even', 'odd'], loop.index) }}">
            <td class="location">{{ entity.location }}</td>
            <td class="position">
                <a href="{{ path('Sm_job_show', { 'id': entity.id, 'company': entity.companyslug, 'location': entity.locationslug, 'position': entity.positionslug }) }}">
                    {{ entity.position }}
                </a>
            </td>
            <td class="company">{{ entity.company }}</td>
        </tr>
    {% endfor %}
</table>

src/Sm/JobsBundle/Resources/views/Job/new.html.twig
{% extends 'JobsBundle::layout.html.twig' %}
 
{% form_theme form _self %}
 
{% block field_errors %}
    {% spaceless %}
        {% if errors|length > 0 %}
            <ul class="error_list">
                {% for error in errors %}
                    <li>{{ error.messageTemplate|trans(error.messageParameters, 'validators') }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endspaceless %}
{% endblock field_errors %}
 
{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/Jobs/css/job.css') }}" type="text/css" media="all" />
{% endblock %}
 
{% block content %}
    <h1>Job creation</h1>
    <form action="{{ path('Sm_job_create') }}" method="post" {{ form_enctype(form) }}>
        <table id="job_form">
            <tfoot>
            <tr>
                <td colspan="2">
                    <input type="submit" value="Preview your job" />
                </td>
            </tr>
            </tfoot>
            <tbody>
            <tr>
                <th>{{ form_label(form.category) }}</th>
                <td>
                    {{ form_errors(form.category) }}
                    {{ form_widget(form.category) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.type) }}</th>
                <td>
                    {{ form_errors(form.type) }}
                    {{ form_widget(form.type) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.company) }}</th>
                <td>
                    {{ form_errors(form.company) }}
                    {{ form_widget(form.company) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.file) }}</th>
                <td>
                    {{ form_errors(form.file) }}
                    {{ form_widget(form.file) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.url) }}</th>
                <td>
                    {{ form_errors(form.url) }}
                    {{ form_widget(form.url) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.position) }}</th>
                <td>
                    {{ form_errors(form.position) }}
                    {{ form_widget(form.position) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.location) }}</th>
                <td>
                    {{ form_errors(form.location) }}
                    {{ form_widget(form.location) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.description) }}</th>
                <td>
                    {{ form_errors(form.description) }}
                    {{ form_widget(form.description) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.how_to_apply) }}</th>
                <td>
                    {{ form_errors(form.how_to_apply) }}
                    {{ form_widget(form.how_to_apply) }}
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.is_public) }}</th>
                <td>
                    {{ form_errors(form.is_public) }}
                    {{ form_widget(form.is_public) }}
                    <br /> Whether the job can also be published on affiliate websites or not.
                </td>
            </tr>
            <tr>
                <th>{{ form_label(form.email) }}</th>
                <td>
                    {{ form_errors(form.email) }}
                    {{ form_widget(form.email) }}
                </td>
            </tr>
            </tbody>
        </table>

        {{ form_rest(form) }}
    </form>
{% endblock %}

src/Sm/JobsBundle/Resources/views/Job/show.html.twig
{% extends 'JobsBundle::layout.html.twig' %}

{% block title %}
    {{ entity.company }} is looking for a {{ entity.position }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('bundles/Jobs/css/job.css') }}" type="text/css" media="all" />
{% endblock %}

{% block content %}
    {% if app.request.get('token') %}
        {% include 'JobsBundle:Job:admin.html.twig' with {'job': entity} %}
    {% endif %}
    <div id="job">
        <h1>{{ entity.company }}</h1>
        <h2>{{ entity.location }}</h2>
        <h3>
            {{ entity.position }}
            <small> - {{ entity.type }}</small>
        </h3>

        {% if entity.logo %}
            <div class="logo">
                <a href="{{ entity.url }}">
                    <img src="/uploads/jobs/{{ entity.logo }}"
                         alt="{{ entity.company }} logo" />
                </a>
            </div>
        {% endif %}

        <div class="description">
            {{ entity.description|nl2br }}
        </div>

        <h4>How to apply?</h4>

        <p class="how_to_apply">{{ entity.howtoapply }}</p>

        <div class="meta">
            <small>posted on {{ entity.createdat|date('m/d/Y') }}</small>
        </div>

        {#<div style="padding: 20px 0">#}
            {#<a href="{{ path('Sm_job_edit', { 'token': entity.token }) }}">#}
                {#Edit#}
            {#</a>#}
        {#</div>#}
    </div>
{% endblock %}